# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_auto_20161031_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='routing_key',
            field=models.CharField(default='channel', help_text='Routing key to decide queue', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(help_text='Channel Name !', max_length=100),
        ),
        migrations.AlterField(
            model_name='channel',
            name='policy',
            field=jsonfield.fields.JSONField(default=b'{"maxRetries": 3}', help_text='Configurable channel policy !'),
        ),
    ]
